export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikx1aXMiLCJlbWFpbCI6ImxjYXNlaXJvQHRlc3QuY29tIiwiaWF0IjoxNzA3NjYyNTYxLCJleHAiOjE3MDgyNjczNjEsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIxIn0.69ixmDtYFVpchA6luaQn9JtqDNhIBqrezGDZpm2NZhU';
